"""Add user profile fields

Revision ID: cb9fad612a02
Revises: d982064a46c5
Create Date: 2025-05-25 18:55:23.080159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9fad612a02'
down_revision: Union[str, None] = 'd982064a46c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('page_title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('page_description', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('twitter_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('instagram_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('linkedin_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('theme_color', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('background_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('background_value', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'background_value')
    op.drop_column('users', 'background_type')
    op.drop_column('users', 'theme_color')
    op.drop_column('users', 'linkedin_username')
    op.drop_column('users', 'instagram_username')
    op.drop_column('users', 'twitter_username')
    op.drop_column('users', 'website')
    op.drop_column('users', 'page_description')
    op.drop_column('users', 'page_title')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
